### ISSUE TITLE
dati non aggiornati

### ISSUE THREAD

**Issue by xrmx** [to-mg/covid-19-piemonte#2]
Lo script funziona ancora ma i dati nel repository non sono più aggiornati dal 28 aprile. Se c'è interesse posso fare una PR per far fare lo scraping tramite actions di github in modo da non perderceli :)

Reference: https://ianwalter.dev/running-selenium-webdriver-tests-using-github-actions/

**Comment by to-mg** [comment]
Grazie per la segnalazione, repository aggiornato
