### ISSUE TITLE
Problemi di aggiornamento

### ISSUE THREAD

**Issue by floatingpurr** [to-mg/covid-19-piemonte#7]
Ciao, ho notato che anche in questo repo ci sono problemi sul caricamento dei dati di oggi. 

Ho in piedi uno scraping analogo degli stessi dati che sta dando problemi da due giorni: https://github.com/floatingpurr/covid-piemonte/runs/1454825338?check_suite_focus=true 

Credo che in entrambi i casi il problema sia dovuto ad alcuni malfunzionamenti della pagina web di origine. Te lo segnalo così da non perdere il file di oggi nella tua serie storica.

**Comment by to-mg** [comment]
io lancio i comandi di scraping manualmente (un paio di script bash),
perché voglio dare un'occhiata ai dati prima di aggiornare git in locale e
su github e perché ogni tanto il sito è in manutenzione. Non avevo ancora
lanciato gli script per i dati del 25, ma una volta che li ho lanciati non
ho ho avuto problemi e ho scaricato anche i dati di ieri. Li trovi su
https://github.com/to-mg/covid-19-piemonte/tree/master/data

Ciao

Mauro

Il giorno mer 25 nov 2020 alle ore 22:50 Andrea <notifications@github.com>
ha scritto:

**Comment by floatingpurr** [comment]
Ok, perfetto! 
Ho preferito avvertirti perché ho visto che ultimamente molte richieste http stanno fallendo frequentemente. E.g.,

```bash
$ curl https://giscovid.sdp.csi.it/tiles/
curl: (52) Empty reply from server
```
...e credevo potessero compromettere qualche tuo processo schedulato.

Ciao!
